version: 2
jobs:
  # Datomic test or test Datomic? Python would go one way for sure.
  datomic-test:
    docker:
      - image: circleci/clojure:tools-deps
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "datomic/deps.edn" }}
      - run:
          name: Install deps
          command: clojure -A:dev:test -e 'nil'
          working_directory: datomic
      - save_cache:
          paths:
            - ~/.m2
          key: v1-{{ checksum "datomic/deps.edn" }}
      - run:
          name: Run tests
          command: clojure -A:test:runner
          working_directory: datomic

  datomic-lint:
    docker:
      - image: borkdude/clj-kondo
    steps:
      - checkout
      - run:
          name: Run clj-kondo
          command: clj-kondo --lint dev dev-resources resources src test
          working_directory: datomic

workflows:
  version: 2
  integrate:
    jobs:
      - datomic-lint
      - datomic-test
