version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:tools-deps
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "deps.edn" }}
      - run: .circleci/deps.sh
      - save_cache:
          paths:
            - ~/.m2
          key: v1-{{ checksum "deps.edn" }}
      - run: bin/test

  lint:
    docker:
      - image: borkdude/clj-kondo
    steps:
      - checkout
      - run: .circleci/lint.sh

workflows:
  version: 2
  integrate:
    jobs:
      - lint
      - test
