version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: please
      POSTGRES_USER: me
  graphql-engine:
    image: hasura/graphql-engine:latest # naughty
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: deathtorest # Tongues firmly in cheeks
      HASURA_GRAPHQL_DATABASE_URL: postgres://me:please@postgres:5432/db
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false' # Use the CLI
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
volumes:
  db_data:
